server:
  port: 8080

spring:
  application:
    name: qr_service
  #datasource:
  #  driver-class-name: com.mysql.jdbc.Driver
  #  url: jdbc:mysql://localhost:3306/qr_service
  #  username: root
  #  password: root
  #jpa:
  #  database-platform: org.hibernate.dialect.MySQL5Dialect
  #  hibernate:
  #    ddl-auto: update
  #  show-sql: true
  #thymeleaf:
  #  cache: false
  #  suffix: .html

